import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Siren, Check, Database } from "lucide-react";
import toast from "react-hot-toast";
import client from "../api/client";
import PageHeader from "../components/ui/PageHeader";
import StatusBadge from "../components/ui/StatusBadge";
import { useAlerts } from "../hooks/useAlerts";
import { containerVariants, cardVariants } from "../components/ui/AnimatedCard";

export default function Alerts() {
  const [filter, setFilter] = useState("ALL");
  const { alerts, count, refresh } = useAlerts(10000);
  const [all, setAll] = useState([]);

  // Load full set (all statuses) once.
  useEffect(() => {
    client.get("/alerts").then((r) => setAll(r.data));
  }, []);

  async function reloadAll() {
    const { data } = await client.get("/alerts");
    setAll(data);
    refresh();
  }

  async function acknowledge(id) {
    await client.patch(`/alerts/${id}/acknowledge`);
    toast.success("Alert acknowledged");
    reloadAll();
  }

  const source = all.length ? all : alerts;
  const list = source.filter((a) => (filter === "ALL" ? true : a.alert_status === filter));

  return (
    <div>
      <PageHeader
        title="Low-Stock Alerts"
        subtitle="Auto-generated by PostgreSQL trigger inventory_low_stock_trigger"
        icon={Siren}
        action={
          <div className="flex items-center gap-2">
            {["ALL", "ACTIVE", "ACKNOWLEDGED", "RESOLVED"].map((f) => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${
                  filter === f ? "bg-cyan/20 text-cyan" : "text-slate-400 hover:bg-white/5"
                }`}
              >
                {f}
              </button>
            ))}
          </div>
        }
      />

      {count > 0 && (
        <motion.div
          initial={{ opacity: 0, x: 30 }}
          animate={{ opacity: 1, x: 0 }}
          className="mb-5 flex items-center gap-3 rounded-2xl border border-danger/30 bg-danger/10 px-4 py-3"
        >
          <span className="h-2.5 w-2.5 rounded-full bg-danger animate-pulseDot" />
          <span className="text-sm font-semibold text-danger">
            {count} active low-stock alert{count > 1 ? "s" : ""} need attention
          </span>
        </motion.div>
      )}

      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3"
      >
        {list.map((a) => (
          <motion.div
            key={a.id}
            variants={cardVariants}
            className="glass rounded-2xl border border-white/10 p-5"
          >
            <div className="flex items-start justify-between">
              <h3 className="font-semibold text-white">{a.product_name}</h3>
              <StatusBadge status={a.alert_status} />
            </div>
            <div className="mt-3 flex items-baseline gap-2">
              <span className="text-3xl font-extrabold text-danger">{a.current_quantity}</span>
              <span className="text-sm text-slate-400">/ {a.threshold} threshold</span>
            </div>
            <div className="mt-1 text-xs text-slate-400">
              Warehouse #{a.warehouse_id} · {a.warehouse_region}
            </div>
            <div className="mt-3 flex items-center gap-1.5 rounded-lg border border-white/10 bg-black/30 px-2 py-1 text-[10px] font-mono text-slate-400">
              <Database size={11} /> Triggered by inventory_low_stock_trigger
            </div>
            {a.alert_status === "ACTIVE" && (
              <button
                onClick={() => acknowledge(a.id)}
                className="mt-4 flex w-full items-center justify-center gap-1.5 rounded-lg bg-white/10 py-2 text-xs font-semibold text-white hover:bg-white/15"
              >
                <Check size={14} /> Acknowledge
              </button>
            )}
          </motion.div>
        ))}
        {list.length === 0 && (
          <p className="col-span-full py-12 text-center text-slate-500">
            No alerts in this view. Auto-resolves when stock is replenished above threshold.
          </p>
        )}
      </motion.div>
    </div>
  );
}
